### ISSUE TITLE
mapper_parsing_exception in version 7.10.1

### ISSUE THREAD

**Issue by dkupper76** [damhau/cucm-cdr#3]
Hello,

I realize that this GitHub Repo is 5 years old, but it is one of the few regarding CUCM CDRs with the ELK Stack. I appreciate the author’s work and contribution to the Community.

I am trying to set this up for ELK/Elastic Stack with release 7.10.1 of Kibana and the corresponding Elasticsearch and Logstash.  Ideally, I want to get this all working inside Docker Containers. I have went through this setup, but I am receiving an error when I try to apply the Elasticsearch Template, the error I am seeing is the following:

{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [cucm-cdr : {_source={enabled=true}, properties={destVideoTransportAddress_Port_Channel2={type=integer}, destVideoTransportAddress_IP_Channel2={type=integer}, origVideoCap_Codec={type=integer}, IncomingProtocolID={type=integer}, origSpan={type=integer}, destMediaCap_g723BitRate={type=integer}, destLegIdentifier={type=integer}, lastRedirectRedirectReason={type=integer}, dateTimeImport={type=date}, origMediaCap_maxFramesPerPacket={type=integer}, origMediaCap_g723BitRate={type=integer}, dateTimeConnect={type=integer}, joinOnBehalfOf={type=integer}, authorizationLevel={type=integer}, origVideoTransportAddress_Port={type=integer}, destConversationId={type=integer}, destMediaTransportAddress_Port={type=integer}, origVideoCap_Codec_Channel2={type=integer}, origVideoTransportAddress_Port_Channel2={type=integer}, destVideoChannel_Role_Channel2={type=integer}, lastRedirectRedirectOnBehalfOf={type=integer}, destSpan={type=integer}, destDTMFMethod={type=integer}, lastRedirectingRoutingReason={type=integer}, origMediaCap_Bandwidth={type=integer}, origCause_location={type=integer}, dateTimeDisconnect_formatted={type=date}, destVideoCap_Codec_Channel2={type=integer}, globalCallID_callId={type=integer}, origLegCallIdentifier={type=integer}, dateTimeOrigination={type=integer}, origRoutingReason={type=integer}, wasCallQueued={type=integer}, dateTimeConnect_formatted={type=date}, destVideoTransportAddress_Port={type=integer}, origVideoChannel_Role_Channel2={type=integer}, origCalledPartyRedirectOnBehalfOf={type=integer}, destVideoCap_Bandwidth_Channel2={type=integer}, destPrecedenceLevel={type=integer}, destVideoCap_Resolution={type=integer}, destMediaCap_Bandwidth={type=integer}, destVideoTransportAddress_IP={type=integer}, origVideoCap_Bandwidth_Channel2={type=integer}, cdrRecordType={type=integer}, calledPartyPatternUsage={type=integer}, origPrecedenceLevel={type=integer}, origVideoCap_Resolution_Channel2={type=integer}, origCause_value={type=integer}, globalCallID_callManagerId={type=integer}, dateTimeDisconnect={type=integer}, origMediaTransportAddress_IP={type=integer}, origMediaTransportAddress_Port={type=integer}, destMediaCap_payloadCapability={type=integer}, destVideoCap_Codec={type=integer}, duration={type=integer}, origVideoCap_Bandwidth={type=integer}, destCause_value={type=integer}, destMediaTransportAddress_IP={type=integer}, origDeviceName={index=not_analyzed, type=string}, destDeviceName={index=not_analyzed, type=string}, OutgoingProtocolID={type=integer}, origVideoTransportAddress_IP_Channel2={type=integer}, origNodeId={type=integer}, origCallTerminationOnBehalfOf={type=integer}, origIpAddr={type=integer}, destNodeId={type=integer}, origCalledPartyRedirectReason={type=integer}, origVideoCap_Resolution={type=integer}, destMediaCap_maxFramesPerPacket={type=integer}, destCallTerminationOnBehalfOf={type=integer}, destVideoCap_Bandwidth={type=integer}, origMediaCap_payloadCapability={type=integer}, callSecuredStatus={type=integer}, origVideoTransportAddress_IP={type=integer}, origConversationId={type=integer}, destVideoCap_Resolution_Channel2={type=integer}, destIpAddr={type=integer}, currentRoutingReason={type=integer}, totalWaitTimeInQueue={type=integer}}}]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [cucm-cdr : {_source={enabled=true}, properties={destVideoTransportAddress_Port_Channel2={type=integer}, destVideoTransportAddress_IP_Channel2={type=integer}, origVideoCap_Codec={type=integer}, IncomingProtocolID={type=integer}, origSpan={type=integer}, destMediaCap_g723BitRate={type=integer}, destLegIdentifier={type=integer}, lastRedirectRedirectReason={type=integer}, dateTimeImport={type=date}, origMediaCap_maxFramesPerPacket={type=integer}, origMediaCap_g723BitRate={type=integer}, dateTimeConnect={type=integer}, joinOnBehalfOf={type=integer}, authorizationLevel={type=integer}, origVideoTransportAddress_Port={type=integer}, destConversationId={type=integer}, destMediaTransportAddress_Port={type=integer}, origVideoCap_Codec_Channel2={type=integer}, origVideoTransportAddress_Port_Channel2={type=integer}, destVideoChannel_Role_Channel2={type=integer}, lastRedirectRedirectOnBehalfOf={type=integer}, destSpan={type=integer}, destDTMFMethod={type=integer}, lastRedirectingRoutingReason={type=integer}, origMediaCap_Bandwidth={type=integer}, origCause_location={type=integer}, dateTimeDisconnect_formatted={type=date}, destVideoCap_Codec_Channel2={type=integer}, globalCallID_callId={type=integer}, origLegCallIdentifier={type=integer}, dateTimeOrigination={type=integer}, origRoutingReason={type=integer}, wasCallQueued={type=integer}, dateTimeConnect_formatted={type=date}, destVideoTransportAddress_Port={type=integer}, origVideoChannel_Role_Channel2={type=integer}, origCalledPartyRedirectOnBehalfOf={type=integer}, destVideoCap_Bandwidth_Channel2={type=integer}, destPrecedenceLevel={type=integer}, destVideoCap_Resolution={type=integer}, destMediaCap_Bandwidth={type=integer}, destVideoTransportAddress_IP={type=integer}, origVideoCap_Bandwidth_Channel2={type=integer}, cdrRecordType={type=integer}, calledPartyPatternUsage={type=integer}, origPrecedenceLevel={type=integer}, origVideoCap_Resolution_Channel2={type=integer}, origCause_value={type=integer}, globalCallID_callManagerId={type=integer}, dateTimeDisconnect={type=integer}, origMediaTransportAddress_IP={type=integer}, origMediaTransportAddress_Port={type=integer}, destMediaCap_payloadCapability={type=integer}, destVideoCap_Codec={type=integer}, duration={type=integer}, origVideoCap_Bandwidth={type=integer}, destCause_value={type=integer}, destMediaTransportAddress_IP={type=integer}, origDeviceName={index=not_analyzed, type=string}, destDeviceName={index=not_analyzed,type=string}, OutgoingProtocolID={type=integer}, origVideoTransportAddress_IP_Channel2={type=integer}, origNodeId={type=integer}, origCallTerminationOnBehalfOf={type=integer}, origIpAddr={type=integer}, destNodeId={type=integer}, origCalledPartyRedirectReason={type=integer}, origVideoCap_Resolution={type=integer}, destMediaCap_maxFramesPerPacket={type=integer}, destCallTerminationOnBehalfOf={type=integer}, destVideoCap_Bandwidth={type=integer}, origMediaCap_payloadCapability={type=integer}, callSecuredStatus={type=integer}, origVideoTransportAddress_IP={type=integer}, origConversationId={type=integer}, destVideoCap_Resolution_Channel2={type=integer}, destIpAddr={type=integer}, currentRoutingReason={type=integer}, totalWaitTimeInQueue={type=integer}}}]","caused_by":{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [cucm-cdr : {_source={enabled=true}, properties={destVideoTransportAddress_Port_Channel2={type=integer}, destVideoTransportAddress_IP_Channel2={type=integer}, origVideoCap_Codec={type=integer}, IncomingProtocolID={type=integer}, origSpan={type=integer}, destMediaCap_g723BitRate={type=integer}, destLegIdentifier={type=integer}, lastRedirectRedirectReason={type=integer}, dateTimeImport={type=date}, origMediaCap_maxFramesPerPacket={type=integer}, origMediaCap_g723BitRate={type=integer}, dateTimeConnect={type=integer}, joinOnBehalfOf={type=integer}, authorizationLevel={type=integer}, origVideoTransportAddress_Port={type=integer}, destConversationId={type=integer}, destMediaTransportAddress_Port={type=integer}, origVideoCap_Codec_Channel2={type=integer}, origVideoTransportAddress_Port_Channel2={type=integer}, destVideoChannel_Role_Channel2={type=integer}, lastRedirectRedirectOnBehalfOf={type=integer}, destSpan={type=integer}, destDTMFMethod={type=integer}, lastRedirectingRoutingReason={type=integer}, origMediaCap_Bandwidth={type=integer}, origCause_location={type=integer}, dateTimeDisconnect_formatted={type=date}, destVideoCap_Codec_Channel2={type=integer}, globalCallID_callId={type=integer}, origLegCallIdentifier={type=integer}, dateTimeOrigination={type=integer}, origRoutingReason={type=integer}, wasCallQueued={type=integer}, dateTimeConnect_formatted={type=date}, destVideoTransportAddress_Port={type=integer}, origVideoChannel_Role_Channel2={type=integer}, origCalledPartyRedirectOnBehalfOf={type=integer}, destVideoCap_Bandwidth_Channel2={type=integer}, destPrecedenceLevel={type=integer}, destVideoCap_Resolution={type=integer}, destMediaCap_Bandwidth={type=integer}, destVideoTransportAddress_IP={type=integer}, origVideoCap_Bandwidth_Channel2={type=integer}, cdrRecordType={type=integer}, calledPartyPatternUsage={type=integer}, origPrecedenceLevel={type=integer}, origVideoCap_Resolution_Channel2={type=integer}, origCause_value={type=integer}, globalCallID_callManagerId={type=integer}, dateTimeDisconnect={type=integer}, origMediaTransportAddress_IP={type=integer}, origMediaTransportAddress_Port={type=integer}, destMediaCap_payloadCapability={type=integer}, destVideoCap_Codec={type=integer}, duration={type=integer}, origVideoCap_Bandwidth={type=integer}, destCause_value={type=integer}, destMediaTransportAddress_IP={type=integer}, origDeviceName={index=not_analyzed, type=string}, destDeviceName={index=not_analyzed, type=string}, OutgoingProtocolID={type=integer}, origVideoTransportAddress_IP_Channel2={type=integer}, origNodeId={type=integer}, origCallTerminationOnBehalfOf={type=integer}, origIpAddr={type=integer}, destNodeId={type=integer}, origCalledPartyRedirectReason={type=integer}, origVideoCap_Resolution={type=integer}, destMediaCap_maxFramesPerPacket={type=integer}, destCallTerminationOnBehalfOf={type=integer}, destVideoCap_Bandwidth={type=integer}, origMediaCap_payloadCapability={type=integer}, callSecuredStatus={type=integer}, origVideoTransportAddress_IP={type=integer}, origConversationId={type=integer}, destVideoCap_Resolution_Channel2={type=integer}, destIpAddr={type=integer}, currentRoutingReason={type=integer}, totalWaitTimeInQueue={type=integer}}}]"}},"status":400}[root@22bea1c5078d /]#

Can you please help or make any suggestions?

Thank you,

Daryl

**Comment by dkupper76** [comment]
Looks like it was a spacing or format error in the file, either that, or rebooting resolved that. However, even though the CDRs are showing up on the Logstash server, and there are no errors that I can see on the Logstash or Elasticsearch server, I am still not getting the CDRs to show up in Kibana or Elastic. Kibana does not have the index available, so I think I am past this initial issue, hopefully I can figure out the next issue, but I am going to close this as I got past the first issue reported, and if I can't get past the next issue, I will open another issue against this.

**Comment by damhau** [comment]
It's great to know that somebody is using this.
I created this for a customer several years ago and I haven't worked on it since but let me know if I can help.
If I find some time I'll try to make it work for newer version of ELK and build a docker image.

I'll look at the issue every week, feel free to open a new one if needed.

**Comment by dkupper76** [comment]
Awesome, I appreciate your reply and possible making of a newer version and Docker image.  

Just to update you, I am now one step closer to getting this all working, I finally am getting data to go from Logstash to Elasticsearch and showing up in Kibana.  In the Learn Logstash section of the elastic website, I found that I needed to run two commands (which are probably very basic for setting up Logstash, but for a newbie to ELK Stack and trying to setup something very quickly, can be overlooked). The commands I am referring to are:

bin/logstash -f first-pipeline.conf --config.test_and_exit

bin/logstash -f first-pipeline.conf --config.reload.automatic

Except I had to use ./logstash -f cucm.conf --config.test_and_exit as I was in the bin directory and I was using the files you provided, though I had to make some modficiations to them, including combining the cucm.conf and elasticsearch.conf into a single .conf file.

Now I am trying to get the visualizations working, but I am seeing the following error:

“There is a problem with this saved object
The saved search associated with this object no longer exists.
If you know what this error means, go ahead and fix it — otherwise click the delete button above.”

The saved search it is referring to is: “search_0” with an ID of: "CUCM-All-Call"

Do you have any idea of what parameters the search was specifying? Was it something like: “cdrRecordType.keyword” or was it something else?

Again I appreciate your help, and if need be, I can open a new issue, but for now, I am trying to figure it out.

Thank you,

Daryl
